<?php
	VRS_RUNTIME_WWW::HTML_TITLE("Incentive Jobs" . VRS_SITE::DEFAULT_TITLE_DOCTOR_SUFFIX);	
	$template = VRS_RUNTIME_WWW::html_template();
	$template->CFG_VAR('main_content_id','container');
	$template->CFG_VAR('page_hide_sidebar', TRUE);
	$template->CFG_VAR('hide_doctype_tag', TRUE);

?>

	<div class="lookingdivs looking1">
		<img id="image" src="<?php echo VRS_RUNTIME_WWW::url_root(); ?>tmpl/images2/VetRelief-Logo-COLOR-withoutappicons.png" />
		<span id="message">
			<h1>Incentive Jobs Page</h1>
			<h3>These practices may accept bids for higher than the going rate.</h3>
		</span>
	</div>
	<div class="lookingdivs looking2">
		<p>(click on the Job ID# for more info or to place a bid)</p>
		<table id="lookingdata">
			<tr>
				<th>Job ID</th>
				<th>Hospital City</th>
				<th>Practice Type</th>
				<th>Dates</th>
			</tr>
		</table>
		<!--There's some dumb shenanigans where adjacent borders merge into one, and there's no elegant way to fix it. So we have to use a br tag to add space here.-->
		<br />
	</div>
	
	<?php 
	include_once(GLOBAL_UNIX_PATH . "libs/class/VRS_FEATURED_ADS.php");
	$ads = new VRS_FEATURED_ADS(VRS_RUNTIME_WWW::site());
	$images = $ads->getDoctorAds();
	?>
	
	<style>
.outer-space {
  overflow: hidden;
}

.box {
  margin:0 auto;
  position: relative;
  z-index: 2;
  padding:10px 0;
}
.box-wrapper {
  position: relative;
  width:100%;
  max-width: 600px;
  margin:0 auto;
}
.box-wrapper:before, .box-wrapper:after {
  content:"";
  position: absolute;
  height:100%;
  width:100vw;
  top: 0;
  z-index: 1;
}
.box-wrapper:before {
  left:-100%;
}
.box-wrapper:after {
  right:-100%;
}

span {
  text-align: center;
  display: block;
}
</style>
<div class="outer-space">
  <div class="">
    <div class="box-wrapper">
      <div class="box">
	  <h6>VetRelief.com Sponsored Jobs (Click image for more info)</h6>
        <div class="ad-carousel" style="float:none;height:fit-content;margin: 0 auto;width:80%">
	  <?php 
	  	foreach ($images as $image) {
	  		echo "<div style=\"text-align: center;\">";
	  
	  		echo "<a href=\"" . $image['link'] . "\" target=\"_blank\"><img src=\"" . VRS_RUNTIME_WWW::url_root() . VRS_FEATURED_ADS::IMAGE_PATH . $image['image_name'] . "\" /></a>";
	  		
	  		echo "</div>";
	  	} ?>
	
	</div>
      </div>
    </div>
  </div>
</div>
	<div id="badgemessage">
		The VetRelief.com Mobile App, Now Available in the App Store and Google Play Store.
	</div>
	
	<div id="badges">
		<span id="apple"><a href="https://apps.apple.com/us/app/vetrelief-com/id1185697277?itsct=apps_box&amp;itscg=30200"><img src="https://tools.applemediaservices.com/api/badges/download-on-the-app-store/black/en-US?size=250x83&amp;releaseDate=1482364800&h=646ad472320ac5866f356f573cea1823" alt="Download on the App Store"></a></span>
		<span id="google"><a href='https://play.google.com/store/apps/details?id=com.goodbarber.vetrelief&pcampaignid=pcampaignidMKT-Other-global-all-co-prtnr-py-PartBadge-Mar2515-1'><img alt='Get it on Google Play' src='https://play.google.com/intl/en_us/badges/static/images/badges/en_badge_web_generic.png'/></a></span>
	</div>
	